name = "tanuinu-accounts-list"
main = "index.js"
compatibility_date = "2026-08-08"

# 毎分実行（1分ごとにVRChat APIをチェックしてKVを更新）
[triggers]
crons = ["* * * * *"]

# D1 データベースの設定
[[d1_databases]]
binding = "DB"
database_name = "vrchat-status-db"
database_id = "9214190c-c6a9-4514-869c-a470714874cc"

# キャッシュ用 KV Namespace の設定
[[kv_namespaces]]
binding = "vrchat-status-db"
id = "0d4fdf8b1974481b8f45fc5675360e2e"
